### PR TITLE
Fix bug in Find command + Add new Functionality

### LINKED ISSUE #48: Fix find command bugs
- AND search not working within same prefixes (i.e. n/alex n/bernice should return a contact that has a name that contains alex and bernice)
- Email search field should allow partial search (i.e. e/@example.com or e/alexyeoh@ should be allowed)

### PR DESCRIPTION
**Pull request by manu2002g**
- Find command should support multi word input eg. find n/Alex Yeoh
- Find command should support substring search for email field
- Update Find command error message to be more helpful

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -122,17 +135,16 @@ public void setPhones(List<Phone> phones) {
...
 
-        public Optional<List<Email>> getEmails() {
+        public Optional<List<String>> getEmails() {
             return Optional.ofNullable(emails);
         }
 
         public Optional<List<String>> getStringEmails() {
-            return getEmails().map(list ->
-                    list.stream().map(name -> name.value).collect(Collectors.toList()));
+            return getEmails();
```
Comment (ongkimlai) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:147]: Not sure if this will break the functionality of other commands. WIll test it out after merging.

**Review by ongkimlai — APPROVED** [review]
Other than my comment, LGTM 👍
